before:
  hooks:
    - go mod download
builds:
  - binary: '{{ .ProjectName }}_{{ .Version }}'
    flags:
      - -trimpath
    goarch:
#      - '386'
      - amd64
#      - arm
#      - arm64
    goos:
      - darwin
#      - freebsd
      - linux
      - windows
    ignore:
      - goarch: '386'
        goos: darwin
    ldflags:
      - -s -w -X version.ProviderVersion={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
changelog:
  skip: true
