# Build customization
builds:
  - binary: terraform-provider-aws
    ldflags: -s -w -X main.VERSION={{.Version}}_Coveo
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386

# Archive customization
archive:
  format: zip

  files:
    - nothing.*
