dist: xenial
sudo: required
services:
  - docker
language: go

env:
  global: GOFLAGS=-mod=vendor

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - go: "1.13.x"
      name: "Code Lint"
      script:
        - golangci-lint run --no-config --deadline 5m --disable-all --enable staticcheck --max-issues-per-linter 0 --max-same-issues 0 -v ./aws
        - golangci-lint run -v ./aws
        - tfproviderlint -c 1 -AT001 -S001 -S002 -S003 -S004 -S005 -S007 -S008 -S009 -S010 -S011 -S012 -S013 -S014 -S015 -S016 -S017 -S019 ./aws
    - go: "1.13.x"
      name: "Code UnitTest"
      script: make test
    - go: "1.13.x"
      name: "Website"
      script:
        - make website-test
        - make website-lint

install:
  # This script is used by the Travis build to install a cookie for
  # go.googlesource.com so rate limits are higher when using `go get` to fetch
  # packages that live there.
  # See: https://github.com/golang/go/issues/12933
  - bash scripts/gogetcookie.sh
  - make tools

branches:
  only:
    - master
