name: Post Publish
on:
  workflow_dispatch:
    inputs:
      release-tag:
        type: string
        description: 'Semver release tag e.g. v1.1.0'
        required: true
  workflow_run:
    workflows: [Release]
    types:
      - completed
jobs:
  on-success-or-workflow-dispatch:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    outputs:
      release-tag: ${{ steps.release-tag.outputs.tag }}
    steps:
      - if: github.event_name == 'workflow_run'
        name: Download Artifact from Release workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: release.yml
          name: release-tag
      - name: Output Release Tag
        id: release-tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "tag=${{ github.event.inputs.release-tag }}" >> "$GITHUB_OUTPUT"
          else
            value=`cat release-tag.data`
            echo "tag=$value" >> "$GITHUB_OUTPUT"
          fi
  tidy-jira:
    needs: [on-success-or-workflow-dispatch]
    runs-on: ubuntu-latest
    steps:
      - name: Tidy Jira
        uses: breathingdust/github-jira-tidy@77daa2cf0f0574bb7be001eb6380939c1af31672
        with:
          jira_host: 'hashicorp.atlassian.net'
          jira_username: 'sdavis@hashicorp.com'
          jira_password: ${{ secrets.jira_password }}
          jira_jql_filter: ${{ secrets.jira_jql_filter }}
          jira_closed_id: '371'
          jira_github_url_field_id: 'cf[10089]'
          github_release_name: ${{ needs.on-success-or-workflow-dispatch.outputs.release-tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  archive-release-cards:
    needs: [on-success-or-workflow-dispatch]
    runs-on: ubuntu-latest
    steps:
      - name: Archive Release Cards
        uses: breathingdust/github-project-archive@4be60b012447c51a5d60d988168f6360815d9ec9
        with:
          github_done_column_id: 11513756
          github_release_name: ${{ needs.on-success-or-workflow-dispatch.outputs.release-tag }}
          github_token: ${{ secrets.ORGSCOPED_GITHUB_TOKEN }}
  coverage:
    needs: [on-success-or-workflow-dispatch]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
        with:
          go-version-file: go.mod
      - run: echo $PATH
      - run: git config --global user.email "github-team-terraform-aws@hashicorp.com"
      - run: git config --global user.name "team-tf-aws"
      - run: go install github.com/breathingdust/duvet@main
      - run: |
          duvet service -f markdown -d docs
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          commit-message: "docs: update coverage stats"
          title: "docs: update coverage stats"
          body: "This PR updates the experimental resource level coverage stats found in the contributor documentation."
          branch: coverage
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
