name: Terraform Provider Tests

on:
  pull_request:
    paths:
      - '.github/workflows/test.yaml'
      - '**.go'

permissions:
  # Permission for checking out code
  contents: read

jobs:
  acceptance:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.2.*'
          terraform_wrapper: false
      - run: go test -v -timeout 180m -cover ./internal/service/ssmincidents/
        env:
          TF_ACC: '1'
          TF_LOG: "DEBUG"
          AWS_DEFAULT_REGION: "us-west-2"
          AWS_ALTERNATE_REGION: "ap-southeast-2"

          # add AWS credentials below:

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: go test -v -cover ./internal/service/ssmincidents/
